/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _T1_H_RPCGEN
#define _T1_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct ATMRecord {
	float valor;
	int senha;
	int targetAccount;
	int thisAccount;
	int clientID;
};
typedef struct ATMRecord ATMRecord;

struct bankRecord {
	int CPF;
	int password;
	int accNumber;
	int clientID;
};
typedef struct bankRecord bankRecord;

struct returnRecord {
	int requesterID;
	float valor;
	int OPResult;
	int completed;
};
typedef struct returnRecord returnRecord;

#define BANK 60125421
#define ATM 1

#if defined(__STDC__) || defined(__cplusplus)
#define SALDO 1
extern  float * saldo_1(ATMRecord *, CLIENT *);
extern  float * saldo_1_svc(ATMRecord *, struct svc_req *);
#define DEPOSITO 2
extern  int * deposito_1(ATMRecord *, CLIENT *);
extern  int * deposito_1_svc(ATMRecord *, struct svc_req *);
#define RETIRADA 3
extern  int * retirada_1(ATMRecord *, CLIENT *);
extern  int * retirada_1_svc(ATMRecord *, struct svc_req *);
#define DEPOSITOFALHA 4
extern  int * depositofalha_1(ATMRecord *, CLIENT *);
extern  int * depositofalha_1_svc(ATMRecord *, struct svc_req *);
#define RETIRADAFALHA 5
extern  int * retiradafalha_1(ATMRecord *, CLIENT *);
extern  int * retiradafalha_1_svc(ATMRecord *, struct svc_req *);
#define REQUESTID 6
extern  int * requestid_1(void *, CLIENT *);
extern  int * requestid_1_svc(void *, struct svc_req *);
#define AUTENTICACAO 7
extern  int * autenticacao_1(ATMRecord *, CLIENT *);
extern  int * autenticacao_1_svc(ATMRecord *, struct svc_req *);
extern int bank_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SALDO 1
extern  float * saldo_1();
extern  float * saldo_1_svc();
#define DEPOSITO 2
extern  int * deposito_1();
extern  int * deposito_1_svc();
#define RETIRADA 3
extern  int * retirada_1();
extern  int * retirada_1_svc();
#define DEPOSITOFALHA 4
extern  int * depositofalha_1();
extern  int * depositofalha_1_svc();
#define RETIRADAFALHA 5
extern  int * retiradafalha_1();
extern  int * retiradafalha_1_svc();
#define REQUESTID 6
extern  int * requestid_1();
extern  int * requestid_1_svc();
#define AUTENTICACAO 7
extern  int * autenticacao_1();
extern  int * autenticacao_1_svc();
extern int bank_1_freeresult ();
#endif /* K&R C */
#define AGENCIA 2

#if defined(__STDC__) || defined(__cplusplus)
extern  float * saldo_2(ATMRecord *, CLIENT *);
extern  float * saldo_2_svc(ATMRecord *, struct svc_req *);
extern  int * deposito_2(ATMRecord *, CLIENT *);
extern  int * deposito_2_svc(ATMRecord *, struct svc_req *);
extern  int * retirada_2(ATMRecord *, CLIENT *);
extern  int * retirada_2_svc(ATMRecord *, struct svc_req *);
extern  int * depositofalha_2(ATMRecord *, CLIENT *);
extern  int * depositofalha_2_svc(ATMRecord *, struct svc_req *);
extern  int * retiradafalha_2(ATMRecord *, CLIENT *);
extern  int * retiradafalha_2_svc(ATMRecord *, struct svc_req *);
extern  int * requestid_2(void *, CLIENT *);
extern  int * requestid_2_svc(void *, struct svc_req *);
extern  int * autenticacao_2(ATMRecord *, CLIENT *);
extern  int * autenticacao_2_svc(ATMRecord *, struct svc_req *);
#define FECHAMENTO 8
extern  int * fechamento_2(bankRecord *, CLIENT *);
extern  int * fechamento_2_svc(bankRecord *, struct svc_req *);
#define ABERTURA 9
extern  int * abertura_2(bankRecord *, CLIENT *);
extern  int * abertura_2_svc(bankRecord *, struct svc_req *);
extern int bank_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  float * saldo_2();
extern  float * saldo_2_svc();
extern  int * deposito_2();
extern  int * deposito_2_svc();
extern  int * retirada_2();
extern  int * retirada_2_svc();
extern  int * depositofalha_2();
extern  int * depositofalha_2_svc();
extern  int * retiradafalha_2();
extern  int * retiradafalha_2_svc();
extern  int * requestid_2();
extern  int * requestid_2_svc();
extern  int * autenticacao_2();
extern  int * autenticacao_2_svc();
#define FECHAMENTO 8
extern  int * fechamento_2();
extern  int * fechamento_2_svc();
#define ABERTURA 9
extern  int * abertura_2();
extern  int * abertura_2_svc();
extern int bank_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_ATMRecord (XDR *, ATMRecord*);
extern  bool_t xdr_bankRecord (XDR *, bankRecord*);
extern  bool_t xdr_returnRecord (XDR *, returnRecord*);

#else /* K&R C */
extern bool_t xdr_ATMRecord ();
extern bool_t xdr_bankRecord ();
extern bool_t xdr_returnRecord ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_T1_H_RPCGEN */
