/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "t1.h"
void printmenucaixa()
{
	printf("[1] consultar saldo\n");
	printf("[2] depositar\n");
	printf("[3] retirar\n");
	printf("[4] depositar falha\n");
	printf("[5] retirar falha\n");
	printf("[e] sair\n\n");
}

void printmenuagencia()
{
	printf("[1] consultar saldo\n");
	printf("[2] depositar\n");
	printf("[3] retirar\n");
	printf("[4] depositar falha\n");
	printf("[5] retirar falha\n");
	printf("[6] abrir conta\n");
	printf("[7] fechar conta\n");
	printf("[e] sair\n\n");
}


void
bank_1(char *host)
{
	CLIENT *clnt;
	float  *valSaldo;
	ATMRecord  saldo;
	int  *depositResult;
	ATMRecord  deposito;
	int  *retiradaResult;
	ATMRecord  retirada;
	int  *depFalhaResult;
	ATMRecord  depositofalha;
	int  *retFalhaResult;
	ATMRecord  retiradafalha;
	int  *ID;
	char *requestid_1_arg;
	int  *authResult;

	char menu = 'x';

#ifndef	DEBUG
	clnt = clnt_create (host, BANK, ATM, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	while(menu != 'e')
	{
		printmenucaixa();
		scanf("%c",&menu);
		switch(menu)
		{
			//###############################SALDO#####################################
			case('1'):
				printf("requesting ID\n");
				ID = requestid_1((void*)&requestid_1_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				saldo.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&saldo.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&saldo.senha);


				authResult = autenticacao_1(&saldo, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				valSaldo = saldo_1(&saldo, clnt);
				if (valSaldo == (float *) NULL) 
				{
					clnt_perror (clnt, "falha no request de saldo");
					break;
				}
				saldo.valor = *valSaldo;
				printf("saldo: %f\n",saldo.valor);
				break;
//###############################DEPOSITO#####################################
			case('2'):
				printf("requesting ID\n");
				ID = requestid_1((void*)&requestid_1_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				deposito.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&deposito.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&deposito.senha);
				printf("digite o valor: ");
				scanf("%f",&deposito.valor);
				authResult = autenticacao_1(&deposito, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				depositResult = deposito_1(&deposito, clnt);
				if (depositResult == (int *) NULL) 
				{
					clnt_perror (clnt, "Deposit failed");
					break;
				}
				if(*depositResult == 1 )
				{
					printf("deposito concluido");
				}
				else
				{
					printf("deposito falhou");
				}
				break;
//###############################RETIRADA#####################################
			case('3'):
				
				ID = requestid_1((void*)&requestid_1_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				retirada.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&retirada.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&retirada.senha);
				printf("digite o valor: ");
				scanf("%f",&retirada.valor);
				printf("requesting ID\n");
				authResult = autenticacao_1(&retirada, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				retiradaResult = retirada_1(&retirada, clnt);
				if (retiradaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "operation failed");
					break;
				}
				if(*retiradaResult == 1 )
				{
					printf("retirada concluida");
				}
				else
				{
					printf("retirada falhou");
				}
				break;
//###############################DEPOSITO COM FALHA#####################################				
			case('4'):
				printf("requesting ID\n");
				ID = requestid_1((void*)&requestid_1_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				depositofalha.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&depositofalha.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&depositofalha.senha);
				printf("digite o valor: ");
				scanf("%f",&depositofalha.valor);
				authResult = autenticacao_1(&depositofalha, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				depFalhaResult = depositofalha_1(&depositofalha, clnt);
				if (depFalhaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "Deposit failed");
					
				}
				if(*depFalhaResult == 1 )
				{
					printf("deposito concluido");
				}
				else
				{
					printf("deposito falhou");
				}
				depFalhaResult = deposito_1(&depositofalha, clnt);
				if (depFalhaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "Deposit failed");
					break;
				}
				if(*depFalhaResult == 1 )
				{
					printf("deposito concluido");
				}
				else
				{
					printf("deposito falhou");
				}
				break;
//###############################DEPOSITO COM FALHA#####################################
			case('5'):
				ID = requestid_1((void*)&requestid_1_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				retiradafalha.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&retiradafalha.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&retiradafalha.senha);
				printf("digite o valor: ");
				scanf("%f",&retiradafalha.valor);
				printf("requesting ID\n");
				authResult = autenticacao_1(&retiradafalha, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				retFalhaResult = retiradafalha_1(&retiradafalha, clnt);
				if (retFalhaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "operation failed");
					
				}
				if(*retFalhaResult == 1 )
				{
					printf("retirada concluida");
				}
				else
				{
					printf("retirada falhou");
				}
				retFalhaResult = retirada_1(&retiradafalha, clnt);
				if (retFalhaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "operation failed");
					break;
				}
				if(*retFalhaResult == 1 )
				{
					printf("retirada concluida");
				}
				else
				{
					printf("retirada falhou");
				}
				break;
			case('e'):
				return;
	
	
		}
	}
#endif	/* DEBUG */

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
bank_2(char *host)
{
	CLIENT *clnt;
	float  *valSaldo;
	ATMRecord  saldo;
	int  *depositResult;
	ATMRecord  deposito;
	int  *retiradaResult;
	ATMRecord  retirada;
	int  *depFalhaResult;
	ATMRecord  depositofalha;
	int  *retFalhaResult;
	ATMRecord  retiradafalha;
	int  *accOpen;
	bankRecord  abertura;
	int  *accClose;
	bankRecord  fechamento;
	int  *result_8;
	ATMRecord  autenticacao_2_arg;
	int  *ID;
	char *requestid_2_arg;
	int *authResult;


	char menu = 'x';

#ifndef	DEBUG
	clnt = clnt_create (host, BANK, AGENCIA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	while(menu != 'e')
	{
		printmenuagencia();
		scanf("%c",&menu);
		switch(menu)
		{
//###############################SALDO#####################################			
			case('1'):
				printf("requesting ID\n");
				ID = requestid_2((void*)&requestid_2_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				saldo.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&saldo.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&saldo.senha);


				authResult = autenticacao_2(&saldo, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				valSaldo = saldo_2(&saldo, clnt);
				if (valSaldo == (float *) NULL) 
				{
					clnt_perror (clnt, "falha no request de saldo");
					break;
				}
				saldo.valor = *valSaldo;
				printf("saldo: %f\n",saldo.valor);
				break;
//###############################DEPOSITO#####################################
			case('2'):
				printf("requesting ID\n");
				ID = requestid_2((void*)&requestid_2_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				deposito.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&deposito.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&deposito.senha);
				printf("digite o valor: ");
				scanf("%f",&deposito.valor);
				authResult = autenticacao_2(&deposito, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				depositResult = deposito_2(&deposito, clnt);
				if (depositResult == (int *) NULL) 
				{
					clnt_perror (clnt, "Deposit failed");
					break;
				}
				if(*depositResult == 1 )
				{
					printf("deposito concluido");
				}
				else
				{
					printf("deposito falhou");
				}
				
//###############################RETIRADA#####################################
			case('3'):
				ID = requestid_2((void*)&requestid_2_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				retirada.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&retirada.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&retirada.senha);
				printf("digite o valor: ");
				scanf("%f",&retirada.valor);
				printf("requesting ID\n");
				authResult = autenticacao_2(&retirada, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				retiradaResult = retirada_2(&retirada, clnt);
				if (retiradaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "operation failed");
					break;
				}
				if(*retiradaResult == 1 )
				{
					printf("retirada concluida");
				}
				else
				{
					printf("retirada falhou");
				}
				break;
//###############################DEPOSITO COM FALHA#####################################
			case('4'):
				printf("requesting ID\n");
				ID = requestid_2((void*)&requestid_2_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				depositofalha.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&depositofalha.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&depositofalha.senha);
				printf("digite o valor: ");
				scanf("%f",&depositofalha.valor);
				authResult = autenticacao_2(&depositofalha, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				depFalhaResult = depositofalha_2(&depositofalha, clnt);
				if (depFalhaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "Deposit failed");
					
				}
				if(*depFalhaResult == 1 )
				{
					printf("deposito concluido");
				}
				else
				{
					printf("deposito falhou");
				}
				depFalhaResult = deposito_2(&depositofalha, clnt);
				if (depFalhaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "Deposit failed");
					break;
				}
				if(*depFalhaResult == 1 )
				{
					printf("deposito concluido");
				}
				else
				{
					printf("deposito falhou");
				}
				break;
//###############################RETIRADA COM FALHA#####################################
			case('5'):
				ID = requestid_2((void*)&requestid_2_arg, clnt);
				if (ID == (int *) NULL)
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				retiradafalha.clientID = *ID;
				printf("digite numero da conta: ");
				scanf("%d",&retiradafalha.thisAccount);
				printf("digite a senha: ");
				scanf("%d",&retiradafalha.senha);
				printf("digite o valor: ");
				scanf("%f",&retiradafalha.valor);
				printf("requesting ID\n");
				authResult = autenticacao_2(&retiradafalha, clnt);
				if (authResult == (int *) NULL) 
				{
					clnt_perror (clnt, "falha no request da autenticacao");
					break;
				}

				if(*authResult == 0)
				{
					printf("Dados errados ou conta inexistente");
					break;
				}
				retFalhaResult = retiradafalha_2(&retiradafalha, clnt);
				if (retFalhaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "operation failed");
					
				}
				if(*retFalhaResult == 1 )
				{
					printf("retirada concluida");
				}
				else
				{
					printf("retirada falhou");
				}
				retFalhaResult = retirada_2(&retiradafalha, clnt);
				if (retFalhaResult == (int *) NULL) 
				{
					clnt_perror (clnt, "operation failed");
					break;
				}
				if(*retFalhaResult == 1 )
				{
					printf("retirada concluida");
				}
				else
				{
					printf("retirada falhou");
				}
				break;

//###############################ABERTURA#####################################
			case('6'):
				ID = requestid_2((void*)&requestid_2_arg, clnt);
				if (ID == (int *) NULL) 
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				abertura.clientID = *ID;
				printf("escolha um numero entre 1 e 10000: ");
				scanf("%d",&abertura.accNumber);
				printf("escolha uma senha de 4 digitos: ");
				scanf("%d",&abertura.password);

				accOpen = abertura_2(&abertura, clnt);
				if (accOpen == (int *) NULL) 
				{
					clnt_perror (clnt, "request de abertura falhou");
					break;
				}
				if(*accOpen == 1)
				{
					printf("account created succesfully\n");
					break;
				}
				else
				{
					printf("account creation failed\n");
					break;
				}
//###############################FECHAMENTO#####################################
			case('7'):
				ID = requestid_2((void*)&requestid_2_arg, clnt);
				if (ID == (int *) NULL) 
				{
					clnt_perror (clnt, "ID request failed");
					break;
				}
				fechamento.clientID = *ID;
				printf("digite o numero da conta que deseja fechar: ");
				scanf("%d",&fechamento.accNumber);
				printf("digite a senha: ");
				scanf("%d",&fechamento.password);

				accClose = fechamento_2(&fechamento, clnt);
				if (accClose == (int *) NULL) 
				{
					clnt_perror (clnt, "request de fechamento falhou");
					break;
				}
				if(*accClose == 1)
				{
					printf("account removed succesfully\n");
					break;
				}
				else
				{
					printf("account removal failed\n");
					break;
				}
			case('e'):
				return;
		}
	}
#endif	/* DEBUG */
/*
	
	result_2 = deposito_2(&deposito_2_arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = retirada_2(&retirada_2_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = depositofalha_2(&depositofalha_2_arg, clnt);
	if (result_4 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = retiradafalha_2(&retiradafalha_2_arg, clnt);
	if (result_5 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	result_7 = fechamento_2(&fechamento_2_arg, clnt);
	if (result_7 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = autenticacao_2(&autenticacao_2_arg, clnt);
	if (result_8 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	}

*/
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int type;
	if (argc < 2) {
		printf ("usage: %s server_host client(1:caixa 2:agencia)\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	type = atoi(argv[2]);
	if(type == 1)
		bank_1 (host);
	else
		bank_2 (host);
exit (0);
}
