/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 * 
 */

#include "t1.h"
#include "conta.h"

#define TOTALCONTAS  10

#define DISPONIVEL  -1
#define OK           1 
#define NOK          0
#define RETIRA     20
#define DEPOSITA     21

Conta static contas[TOTALCONTAS] = {
	{666, 123456, 606.06},
	{ -1,      0,   0.00},
	{ -1,      0,   0.00},
	{ -1,      0,   0.00},
	{ -1,      0,   0.00},
	{ -1,      0,   0.00},
	{ -1,      0,   0.00},
	{ -1,      0,   0.00},
	{ -1,      0,   0.00},
	{ -1,      0,   0.00},
};

int static requestID = 0;


int ValidarConta( ATMRecord *argp )
{
	int result;
 	for (int i = 0; i < TOTALCONTAS; i++)
	{
		if ( (argp->thisAccount  == contas[i].Account) && 
		     (argp->senha  == contas[i].Senha) )
		{
			result = OK;
			break;
		}
		else
		{
			result = NOK;
		}		
	}

	return result;
}


float EncontraSaldo (ATMRecord *argp)
{
	static float result;
	fprintf(stderr,"Starting EncontraSaldo for account %d\n",argp->thisAccount);
	for (int i = 0; i < TOTALCONTAS; i++)
	{
		if ( argp->thisAccount == contas[i].Account)
		{
			result = contas[i].Saldo;
		}
	}
	fprintf(stderr,"Finishing EncontraSaldo for account %d\n",argp->thisAccount);
	return result;
}

int ManipularSaldo (ATMRecord *argp, int operacao)
{
	static int result;
	fprintf(stderr,"Starting ManipularSaldo for account %d\n",argp->thisAccount);
	for (int i = 0; i < TOTALCONTAS; i++)
	{
		if ( ( contas[i].Account == argp->thisAccount ))
		{
			switch (operacao)
			{
				case DEPOSITA:
					contas[i].Saldo += argp->valor;	
				break;

				case RETIRA:
					contas[i].Saldo -= argp->valor;	
				break;
			}

			
			result = OK;
			break;
		}
		else
		{
			result = NOK;
		}		
	}
	fprintf(stderr,"Finishing ManipularSaldo for account %d\n",argp->thisAccount);
	return result;	
}

float *
saldo_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static float  result;

	result = EncontraSaldo( argp );	

	return &result;
}

int *
deposito_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	result = ManipularSaldo( argp, DEPOSITA);

	return &result;
}

int *
retirada_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	result = ManipularSaldo( argp, RETIRA);

	return &result;
}

int *
depositofalha_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retiradafalha_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}


// Gera o Numero unico para transacoes
int *
requestid_1_svc(void *argp, struct svc_req *rqstp)
{
	fprintf(stderr,"RequestID started\n");
	static int  result;	

	result = requestID++;
	fprintf(stderr,"Returning ID %d\n",result);
	return &result;
}

int *
autenticacao_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{	
	fprintf(stderr,"Autentication started\n");
	static int  result;

	result = ValidarConta( argp );
	fprintf(stderr,"Autentication finished with %d\n",result);
	return &result;
}

float *
saldo_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static float  result;

	result = EncontraSaldo( argp );

	return &result;
}

int *
deposito_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	result = ManipularSaldo( argp, DEPOSITA);

	return &result;
}

int *
retirada_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	result = ManipularSaldo( argp, RETIRA );

	return &result;
}

int *
depositofalha_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retiradafalha_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
requestid_2_svc(void *argp, struct svc_req *rqstp)
{
	fprintf(stderr,"Request ID started\n");
	static int  result;

	result = requestID++;
	fprintf(stderr,"Returning ID %d\n",result);
	return &result;
}

int *
autenticacao_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	fprintf(stderr,"Autentication started\n");
	static int  result;

	result = ValidarConta( argp );
	fprintf(stderr,"Autentication finished\n");
	return &result;
}

int *
fechamento_2_svc(bankRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
abertura_2_svc(bankRecord *argp, struct svc_req *rqstp)
{
	fprintf(stderr,"Acc Opening started\n");
	static int  result;
	int debug;
	for (int i = 0; i < TOTALCONTAS; i++)
	{
		if ( contas[i].Account == DISPONIVEL )
		{
			contas[i].Account = argp->accNumber;
			contas[i].Senha = argp->password;

			result = OK;

			debug = i;
			break;
		}
		else
		{
			result = NOK;
		}
		
	}
	fprintf(stderr,"Acc Opening concluced for %d with pass %d\n",contas[debug].Account,contas[debug].Senha);
	return &result;
}
