/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 * 
 */

#include "t1.h"
#include "conta.h"

#define TOTALCONTAS 10

Conta contas[TOTALCONTAS];

int static requestID = 0;


int ValidarConta( ATMRecord *argp )
{
	int result;
 	for (int i = 0; i < TOTALCONTAS; i++)
	{
		if ( (argp->clientID  == contas[i].ClientID) && 
		     (argp->senha  == contas[i].Senha) )
		{
			result = 1;
		}
		else
		{
			result = 0;
		}		
	}

	return result;
}

float *
saldo_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
deposito_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retirada_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
depositofalha_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retiradafalha_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}


// Gera o Numero unico para transacoes
int *
requestid_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;	

	result = requestID++;

	fprintf("[requestid_1_svc] = %d", result);

	return &result;
}

int *
autenticacao_1_svc(ATMRecord *argp, struct svc_req *rqstp)
{	
	static int  result;

	result = ValidarConta( &argp );
	
	fprintf("[autenticacao_1_svc] = %d", result);

	return &result;
}

float *
saldo_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static float  result;

	if ( ValidarConta( &argp ) == 1 )
	{
		resul
	}
	

	return &result;
}

int *
deposito_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retirada_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
depositofalha_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
retiradafalha_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
requestid_2_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	result = requestID++;

	fprintf("[requestid_2_svc] = %d", result);

	return &result;
}

int *
autenticacao_2_svc(ATMRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
fechamento_2_svc(bankRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
abertura_2_svc(bankRecord *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
