/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "t1.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
bank_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ATMRecord saldo_1_arg;
		ATMRecord deposito_1_arg;
		ATMRecord retirada_1_arg;
		ATMRecord depositofalha_1_arg;
		ATMRecord retiradafalha_1_arg;
		ATMRecord autenticacao_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SALDO:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) saldo_1_svc;
		break;

	case DEPOSITO:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) deposito_1_svc;
		break;

	case RETIRADA:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) retirada_1_svc;
		break;

	case DEPOSITOFALHA:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) depositofalha_1_svc;
		break;

	case RETIRADAFALHA:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) retiradafalha_1_svc;
		break;

	case REQUESTID:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) requestid_1_svc;
		break;

	case AUTENTICACAO:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) autenticacao_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
bank_2(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		ATMRecord saldo_2_arg;
		ATMRecord deposito_2_arg;
		ATMRecord retirada_2_arg;
		ATMRecord depositofalha_2_arg;
		ATMRecord retiradafalha_2_arg;
		ATMRecord autenticacao_2_arg;
		bankRecord fechamento_2_arg;
		bankRecord abertura_2_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SALDO:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_float;
		local = (char *(*)(char *, struct svc_req *)) saldo_2_svc;
		break;

	case DEPOSITO:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) deposito_2_svc;
		break;

	case RETIRADA:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) retirada_2_svc;
		break;

	case DEPOSITOFALHA:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) depositofalha_2_svc;
		break;

	case RETIRADAFALHA:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) retiradafalha_2_svc;
		break;

	case REQUESTID:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) requestid_2_svc;
		break;

	case AUTENTICACAO:
		_xdr_argument = (xdrproc_t) xdr_ATMRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) autenticacao_2_svc;
		break;

	case FECHAMENTO:
		_xdr_argument = (xdrproc_t) xdr_bankRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) fechamento_2_svc;
		break;

	case ABERTURA:
		_xdr_argument = (xdrproc_t) xdr_bankRecord;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) abertura_2_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (BANK, ATM);
	pmap_unset (BANK, AGENCIA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, BANK, ATM, bank_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (BANK, ATM, udp).");
		exit(1);
	}
	if (!svc_register(transp, BANK, AGENCIA, bank_2, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (BANK, AGENCIA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, BANK, ATM, bank_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (BANK, ATM, tcp).");
		exit(1);
	}
	if (!svc_register(transp, BANK, AGENCIA, bank_2, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (BANK, AGENCIA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
