/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "t1.h"

bool_t
xdr_ATMRecord (XDR *xdrs, ATMRecord *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_float (xdrs, &objp->valor))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->senha))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->targetAccount))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->thisAccount))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->clientID))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->senha);
			IXDR_PUT_LONG(buf, objp->targetAccount);
			IXDR_PUT_LONG(buf, objp->thisAccount);
			IXDR_PUT_LONG(buf, objp->clientID);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_float (xdrs, &objp->valor))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->senha))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->targetAccount))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->thisAccount))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->clientID))
				 return FALSE;
		} else {
			objp->senha = IXDR_GET_LONG(buf);
			objp->targetAccount = IXDR_GET_LONG(buf);
			objp->thisAccount = IXDR_GET_LONG(buf);
			objp->clientID = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_float (xdrs, &objp->valor))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->senha))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->targetAccount))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->thisAccount))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->clientID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_bankRecord (XDR *xdrs, bankRecord *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->CPF))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->password))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->accNumber))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->clientID))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->CPF);
			IXDR_PUT_LONG(buf, objp->password);
			IXDR_PUT_LONG(buf, objp->accNumber);
			IXDR_PUT_LONG(buf, objp->clientID);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->CPF))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->password))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->accNumber))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->clientID))
				 return FALSE;
		} else {
			objp->CPF = IXDR_GET_LONG(buf);
			objp->password = IXDR_GET_LONG(buf);
			objp->accNumber = IXDR_GET_LONG(buf);
			objp->clientID = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->CPF))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->password))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->accNumber))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->clientID))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_returnRecord (XDR *xdrs, returnRecord *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->requesterID))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->valor))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->OPResult))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->completed))
		 return FALSE;
	return TRUE;
}
