/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
addprog_1(char *host, int x , int y)
{
	CLIENT *clnt;
	int  *result_1;
	record  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADDPROG, ADDVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		printf("deu cu");
		exit (1);
	}
	printf("requisitando");
#endif	/* DEBUG */
	add_1_arg.x = x;
	add_1_arg.y = y;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("resultado == %d",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int x,y;
	if (argc < 4) {
		printf ("usage: %s server_host num1 num2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	x = atoi(argv[2]);
	y = atoi(argv[3]);
	addprog_1 (host,x,y);
exit (0);
}
